version: '3.3'

services:
  web:
    build: .
    image: bamorgan13/eventlight
    ports:
      - 5000:5000
    networks:
      - eventlight
    env_file:
      - .env
  db:
    image: mongo:4.2
    volumes:
      - mongo-db:/data/db
    networks:
      eventlight:
        aliases:
          - 'mongo_db'

networks:
  eventlight:
    driver: bridge
volumes:
  mongo-db:
